name: Elixir CI

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:

    name: Check code styles and run tests
    runs-on: ubuntu-22.04


    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.6' # Define the elixir version [required]
        otp-version: '26' # Define the OTP version [required]
        experimental-otp: true #https://github.com/actions/setup-elixir/issues/49
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Check lints
      run: make lint


